### PR TITLE
move from newtonsoft to system.text.json

### PR DESCRIPTION
**Pull request by madhon**
This work should solve #594  by moving from Newtonsoft.Json to System.Text.Json

### CODE REVIEW

**Comment by KleberSyd** [comment]
Could we do it @abbasc52 , for sure it is a breaking change, but it is useful.

**Comment by asulwer** [comment]
working on this now in my fork

**Comment by YogeshPraj** [comment]
Hi @madhon ,
Sorry for the delay, Can you please resolve the conflict? I will approve it

**Review by YogeshPraj — APPROVED** [review]

**Comment by madhon** [comment]
> Hi @madhon , Sorry for the delay, Can you please resolve the conflict? I will approve it

Sorry missed this as it was overnight my time, what was the conflict ?

**Pull request merged**
